language: rust
before_install:
  - rustup component add rustfmt
  - rustup component add clippy
install:
  - cargo build --verbose --all-targets
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
  - cargo build --verbose --all-targets
  - cargo test --verbose --all-targets
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

